### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#3]
This is largely based on the featureset needed by google-cloud-python and the features provided by google-auth-library-nodejs.

Required features:
- [x] JWT signing and verification using PEM keys. (#6, #7)
- [x] JWT credentials. (#21)
- [x] Compute Engine credentials. (#11, #22)
- [x] App Engine credentials. (#
- [x] Service Account (JWT Grant for OAuth 2.0) credentials. (#13, #25)
- [x] OAuth 2.0 Access Token credentials (no flows, credentials only for ADC). (#13, #24)
- [x] Implementation of [application default credentials](https://developers.google.com/identity/protocols/application-default-credentials), along with the ability to determine the project ID. (#32)
- [x] Well-defined transport interface, with ability for users to build their own. (#10)
- [x] urllib3 support. (#14)
- [x] Ability to convert oauth2client credentials. (#36)

Nice to have:
- [x] requests support. (#37) 
- [ ] helper to verify Google-signed ID tokens [oauth2client's implementation](https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L1519). (#39)

oauth2client features explicitly not in scope for 1.0.0:
- OAuth 2.0 flows.
- Storage. (Discussion at #33)
- Devshell credentials (seems to only be used by the gcloud cli).
- Django, Flask, and Webapp2 helpers.
- httplib2 support. (Temporary support in #34)

**Comment by dhermes** [comment]
It's probably worth having a plugin / extensibility story for transports in the 1.0.0

**Comment by jonparrott** [comment]
@dhermes updated.

**Comment by jonparrott** [comment]
All essentially functionality has been implemented. Closing.
